from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import JSON, DateTime, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from storybard.core.db import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Campaign(Base):
    __tablename__ = "campaigns"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(200), index=True)
    mode: Mapped[str] = mapped_column(String(32), default="explore")

    active_narrator_profile_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    calendar_name: Mapped[str] = mapped_column(String(128), default="Gregorian")
    current_datetime: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    # Advanced by each turn's Plausibility Check `time_passed` output (see
    # chain/service.py::_apply_plausibility_time) — nothing else mutates current_datetime.
    last_world_tick_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    turn_count: Mapped[int] = mapped_column(Integer, default=0)

    # Rolling campaign summary — a field, not a separate table (see spec.md). Rewritten
    # every turn by Memory Regression (chain/service.py::_apply_memory_regression) to
    # reflect "where the story stands now" — the GM's compressed long-horizon memory,
    # complementing the short tactical recent_turns window.
    summary: Mapped[str] = mapped_column(Text, default="")

    # The one-time scene-setting narration generated by api/turns.py's opening-scene
    # endpoint — deliberately separate from `summary` (which is rolling and rewritten every
    # turn); conflating the two meant `summary` could never actually roll after turn 0.
    opening_narration: Mapped[str | None] = mapped_column(Text, nullable=True)

    tone_state: Mapped[dict] = mapped_column(JSON, default=dict)

    # Descriptive starting-calendar flavor ("early winter, three days before the harvest
    # festival") generated from the campaign pitch — deliberately free text, not parsed
    # into current_datetime (fragile for the value it'd add); same category as scene_text.
    # Session-zero content (safety_tools, personal_stakes) captured during seeding, fed
    # into opening_scene_prompt/narrator_prompt. All three nullable: pre-existing
    # campaigns and campaigns with seed_session_zero/seed_calendar_from_pitch off won't
    # have them. See the "All 20 Features" plan.
    calendar_context: Mapped[str | None] = mapped_column(Text, nullable=True)
    safety_tools: Mapped[str | None] = mapped_column(Text, nullable=True)
    personal_stakes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
