"""add campaign.opening_narration and actor.current_goal

Revision ID: 3c4ea9cb69df
Revises: 4f44914908f4
Create Date: 2026-09-28 23:17:17.429309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4ea9cb69df'
down_revision: Union[str, Sequence[str], None] = '4f44914908f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('current_goal', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('opening_narration', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'opening_narration')
    op.drop_column('actors', 'current_goal')
    # ### end Alembic commands ###
