"""add memory created_at for recency ordering

Revision ID: 4f44914908f4
Revises: d7530d9ae43a
Create Date: 2026-09-28 22:43:12.445494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f44914908f4'
down_revision: Union[str, Sequence[str], None] = 'd7530d9ae43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (same pattern as d7530d9ae43a), dropped again
    # right after so the column matches the model exactly (Python-level default only).
    op.add_column(
        'memories',
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )
    op.alter_column('memories', 'created_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'created_at')
    # ### end Alembic commands ###
