"""actor speech style

Revision ID: 579b46e28a74
Revises: 6a849fdaac42
Create Date: 2026-09-30 17:18:49.679273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579b46e28a74'
down_revision: Union[str, Sequence[str], None] = '6a849fdaac42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('speech_style', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'speech_style')
    # ### end Alembic commands ###
