"""thread beats

Revision ID: 6a849fdaac42
Revises: d44be23e56fa
Create Date: 2026-09-29 18:03:51.964260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a849fdaac42'
down_revision: Union[str, Sequence[str], None] = 'd44be23e56fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_beats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_thread_beats_thread_id_threads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thread_beats'))
    )
    op.create_index(op.f('ix_thread_beats_thread_id'), 'thread_beats', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_beats_thread_id'), table_name='thread_beats')
    op.drop_table('thread_beats')
    # ### end Alembic commands ###
