"""campaign settings, inventory, planted reveals, campaign flavor text

Revision ID: a4bafed30180
Revises: 3c4ea9cb69df
Create Date: 2026-09-29 12:59:30.792122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bafed30180'
down_revision: Union[str, Sequence[str], None] = '3c4ea9cb69df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_settings',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('seed_npc_count', sa.Integer(), nullable=False),
    sa.Column('seed_hook_count', sa.Integer(), nullable=False),
    sa.Column('seed_npc_relationships', sa.Boolean(), nullable=False),
    sa.Column('seed_rumor_count', sa.Integer(), nullable=False),
    sa.Column('seed_location_depth', sa.Integer(), nullable=False),
    sa.Column('seed_calendar_from_pitch', sa.Boolean(), nullable=False),
    sa.Column('seed_always_faction', sa.Boolean(), nullable=False),
    sa.Column('seed_session_zero', sa.Boolean(), nullable=False),
    sa.Column('seed_starting_inventory', sa.Boolean(), nullable=False),
    sa.Column('seed_starting_inventory_count', sa.Integer(), nullable=False),
    sa.Column('seed_planted_reveal', sa.Boolean(), nullable=False),
    sa.Column('narration_npc_offscreen', sa.Boolean(), nullable=False),
    sa.Column('narration_npc_offscreen_interval_hours', sa.Integer(), nullable=False),
    sa.Column('narration_twist_enabled', sa.Boolean(), nullable=False),
    sa.Column('narration_twist_frequency', sa.Integer(), nullable=False),
    sa.Column('narration_npc_voices', sa.Boolean(), nullable=False),
    sa.Column('narration_consequence_ledger', sa.Boolean(), nullable=False),
    sa.Column('narration_hard_stagnation_threshold', sa.Integer(), nullable=False),
    sa.Column('mechanical_degrees_of_success', sa.Boolean(), nullable=False),
    sa.Column('narration_thinking_gloss', sa.Boolean(), nullable=False),
    sa.Column('narration_oracle_enabled', sa.Boolean(), nullable=False),
    sa.Column('narration_npc_memory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id', name=op.f('pk_campaign_settings'))
    )
    op.create_table('planted_reveals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('secret_text', sa.Text(), nullable=False),
    sa.Column('connects_entity_ids', sa.JSON(), nullable=False),
    sa.Column('revealed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planted_reveals'))
    )
    op.create_index(op.f('ix_planted_reveals_campaign_id'), 'planted_reveals', ['campaign_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('owner_actor_id', sa.UUID(), nullable=False),
    sa.Column('item_def_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_def_id'], ['item_defs.id'], name=op.f('fk_inventory_items_item_def_id_item_defs')),
    sa.ForeignKeyConstraint(['owner_actor_id'], ['actors.id'], name=op.f('fk_inventory_items_owner_actor_id_actors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    op.create_index(op.f('ix_inventory_items_campaign_id'), 'inventory_items', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_def_id'), 'inventory_items', ['item_def_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_owner_actor_id'), 'inventory_items', ['owner_actor_id'], unique=False)
    op.add_column('campaigns', sa.Column('calendar_context', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('safety_tools', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('personal_stakes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'personal_stakes')
    op.drop_column('campaigns', 'safety_tools')
    op.drop_column('campaigns', 'calendar_context')
    op.drop_index(op.f('ix_inventory_items_owner_actor_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_def_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_campaign_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_planted_reveals_campaign_id'), table_name='planted_reveals')
    op.drop_table('planted_reveals')
    op.drop_table('campaign_settings')
    # ### end Alembic commands ###
