"""initial schema

Revision ID: cf6d6a1eefa9
Revises: 
Create Date: 2026-09-28 20:04:57.604122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6d6a1eefa9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('abbreviation', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_definitions'))
    )
    op.create_index(op.f('ix_attribute_definitions_campaign_id'), 'attribute_definitions', ['campaign_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('active_narrator_profile_id', sa.UUID(), nullable=True),
    sa.Column('calendar_name', sa.String(length=128), nullable=False),
    sa.Column('current_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tone_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_table('factions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('reputation_baseline', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factions'))
    )
    op.create_index(op.f('ix_factions_campaign_id'), 'factions', ['campaign_id'], unique=False)
    op.create_table('hooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('touches_entity_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hooks'))
    )
    op.create_index(op.f('ix_hooks_campaign_id'), 'hooks', ['campaign_id'], unique=False)
    op.create_table('narrator_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('style_description', sa.Text(), nullable=False),
    sa.Column('verbosity_target_words', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_narrator_profiles'))
    )
    op.create_index(op.f('ix_narrator_profiles_campaign_id'), 'narrator_profiles', ['campaign_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('parent_thread_id', sa.UUID(), nullable=True),
    sa.Column('relation', sa.String(length=32), nullable=True),
    sa.Column('owner_type', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_thread_id'], ['threads.id'], name=op.f('fk_threads_parent_thread_id_threads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads'))
    )
    op.create_index(op.f('ix_threads_campaign_id'), 'threads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_threads_parent_thread_id'), 'threads', ['parent_thread_id'], unique=False)
    op.create_table('turn_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action_text', sa.String(length=4000), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('final_narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turn_runs'))
    )
    op.create_index(op.f('ix_turn_runs_actor_id'), 'turn_runs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_turn_runs_campaign_id'), 'turn_runs', ['campaign_id'], unique=False)
    op.create_table('world_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_long', sa.Text(), nullable=True),
    sa.Column('danger_level', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_nodes'))
    )
    op.create_index(op.f('ix_world_nodes_campaign_id'), 'world_nodes', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_world_nodes_name'), 'world_nodes', ['name'], unique=False)
    op.create_table('actors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('current_node_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['current_node_id'], ['world_nodes.id'], name=op.f('fk_actors_current_node_id_world_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actors'))
    )
    op.create_index(op.f('ix_actors_campaign_id'), 'actors', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_actors_name'), 'actors', ['name'], unique=False)
    op.create_table('chain_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turn_run_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.Column('final_output', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['turn_run_id'], ['turn_runs.id'], name=op.f('fk_chain_steps_turn_run_id_turn_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_steps'))
    )
    op.create_index(op.f('ix_chain_steps_turn_run_id'), 'chain_steps', ['turn_run_id'], unique=False)
    op.create_table('clocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('segments_total', sa.Integer(), nullable=False),
    sa.Column('segments_filled', sa.Integer(), nullable=False),
    sa.Column('tick_source', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('consequence_op', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_clocks_thread_id_threads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clocks'))
    )
    op.create_index(op.f('ix_clocks_thread_id'), 'clocks', ['thread_id'], unique=False)
    op.create_table('actor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_actor_profiles_actor_id_actors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actor_profiles'))
    )
    op.create_index(op.f('ix_actor_profiles_actor_id'), 'actor_profiles', ['actor_id'], unique=True)
    op.create_table('character_sheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('ancestry', sa.String(length=64), nullable=True),
    sa.Column('character_class', sa.String(length=64), nullable=True),
    sa.Column('ability_scores', sa.JSON(), nullable=False),
    sa.Column('proficiencies', sa.JSON(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_character_sheets_actor_id_actors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_sheets'))
    )
    op.create_index(op.f('ix_character_sheets_actor_id'), 'character_sheets', ['actor_id'], unique=True)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('owner_actor_id', sa.UUID(), nullable=False),
    sa.Column('subject_actor_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_actor_id'], ['actors.id'], name=op.f('fk_memories_owner_actor_id_actors')),
    sa.ForeignKeyConstraint(['subject_actor_id'], ['actors.id'], name=op.f('fk_memories_subject_actor_id_actors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_index(op.f('ix_memories_campaign_id'), 'memories', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_memories_owner_actor_id'), 'memories', ['owner_actor_id'], unique=False)
    op.create_index(op.f('ix_memories_subject_actor_id'), 'memories', ['subject_actor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_subject_actor_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_owner_actor_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_campaign_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_character_sheets_actor_id'), table_name='character_sheets')
    op.drop_table('character_sheets')
    op.drop_index(op.f('ix_actor_profiles_actor_id'), table_name='actor_profiles')
    op.drop_table('actor_profiles')
    op.drop_index(op.f('ix_clocks_thread_id'), table_name='clocks')
    op.drop_table('clocks')
    op.drop_index(op.f('ix_chain_steps_turn_run_id'), table_name='chain_steps')
    op.drop_table('chain_steps')
    op.drop_index(op.f('ix_actors_name'), table_name='actors')
    op.drop_index(op.f('ix_actors_campaign_id'), table_name='actors')
    op.drop_table('actors')
    op.drop_index(op.f('ix_world_nodes_name'), table_name='world_nodes')
    op.drop_index(op.f('ix_world_nodes_campaign_id'), table_name='world_nodes')
    op.drop_table('world_nodes')
    op.drop_index(op.f('ix_turn_runs_campaign_id'), table_name='turn_runs')
    op.drop_index(op.f('ix_turn_runs_actor_id'), table_name='turn_runs')
    op.drop_table('turn_runs')
    op.drop_index(op.f('ix_threads_parent_thread_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_campaign_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_narrator_profiles_campaign_id'), table_name='narrator_profiles')
    op.drop_table('narrator_profiles')
    op.drop_index(op.f('ix_hooks_campaign_id'), table_name='hooks')
    op.drop_table('hooks')
    op.drop_index(op.f('ix_factions_campaign_id'), table_name='factions')
    op.drop_table('factions')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_attribute_definitions_campaign_id'), table_name='attribute_definitions')
    op.drop_table('attribute_definitions')
    # ### end Alembic commands ###
