"""character sheet conditions

Revision ID: d44be23e56fa
Revises: a4bafed30180
Create Date: 2026-09-29 15:27:18.459800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44be23e56fa'
down_revision: Union[str, Sequence[str], None] = 'a4bafed30180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows (e.g. characters already in play), then gets
    # dropped so future inserts rely on the ORM-level default instead — same pattern used
    # by every other backfilled column added mid-project (see prior migrations' comments).
    op.add_column(
        'character_sheets', sa.Column('conditions', sa.JSON(), nullable=False, server_default='[]')
    )
    op.alter_column('character_sheets', 'conditions', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_sheets', 'conditions')
    # ### end Alembic commands ###
