"""phase 3a: location hierarchy, entity defs, time passage

Revision ID: d7530d9ae43a
Revises: cf6d6a1eefa9
Create Date: 2026-09-28 21:51:39.493872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7530d9ae43a'
down_revision: Union[str, Sequence[str], None] = 'cf6d6a1eefa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ancestry_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ancestry_defs'))
    )
    op.create_index(op.f('ix_ancestry_defs_campaign_id'), 'ancestry_defs', ['campaign_id'], unique=False)
    op.create_table('class_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hit_die', sa.Integer(), nullable=False),
    sa.Column('primary_attribute_key', sa.String(length=32), nullable=False),
    sa.Column('proficiencies', sa.JSON(), nullable=False),
    sa.Column('spellcasting', sa.Boolean(), nullable=False),
    sa.Column('starting_equipment', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_defs'))
    )
    op.create_index(op.f('ix_class_defs_campaign_id'), 'class_defs', ['campaign_id'], unique=False)
    op.create_table('item_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_defs'))
    )
    op.create_index(op.f('ix_item_defs_campaign_id'), 'item_defs', ['campaign_id'], unique=False)
    op.create_table('spell_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=32), nullable=False),
    sa.Column('casting_time', sa.String(length=64), nullable=False),
    sa.Column('range', sa.String(length=64), nullable=False),
    sa.Column('duration', sa.String(length=64), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spell_defs'))
    )
    op.create_index(op.f('ix_spell_defs_campaign_id'), 'spell_defs', ['campaign_id'], unique=False)
    # server_default backfills existing rows (this dev DB has live-verification data from
    # prior phases worth keeping, unlike 2A's drop/recreate) — dropped again right after so
    # the column matches the model exactly (Python-level default only, no DB-level default).
    op.add_column(
        'campaigns',
        sa.Column('last_world_tick_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )
    op.alter_column('campaigns', 'last_world_tick_at', server_default=None)
    op.add_column('clocks', sa.Column('real_time_per_segment', sa.Interval(), nullable=True))
    op.add_column('threads', sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('threads', 'priority', server_default=None)
    op.add_column('world_nodes', sa.Column('parent_node_id', sa.UUID(), nullable=True))
    op.add_column('world_nodes', sa.Column('depth', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('world_nodes', 'depth', server_default=None)
    op.add_column('world_nodes', sa.Column('scale', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_world_nodes_parent_node_id'), 'world_nodes', ['parent_node_id'], unique=False)
    op.create_foreign_key(op.f('fk_world_nodes_parent_node_id_world_nodes'), 'world_nodes', 'world_nodes', ['parent_node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_world_nodes_parent_node_id_world_nodes'), 'world_nodes', type_='foreignkey')
    op.drop_index(op.f('ix_world_nodes_parent_node_id'), table_name='world_nodes')
    op.drop_column('world_nodes', 'scale')
    op.drop_column('world_nodes', 'depth')
    op.drop_column('world_nodes', 'parent_node_id')
    op.drop_column('threads', 'priority')
    op.drop_column('clocks', 'real_time_per_segment')
    op.drop_column('campaigns', 'last_world_tick_at')
    op.drop_index(op.f('ix_spell_defs_campaign_id'), table_name='spell_defs')
    op.drop_table('spell_defs')
    op.drop_index(op.f('ix_item_defs_campaign_id'), table_name='item_defs')
    op.drop_table('item_defs')
    op.drop_index(op.f('ix_class_defs_campaign_id'), table_name='class_defs')
    op.drop_table('class_defs')
    op.drop_index(op.f('ix_ancestry_defs_campaign_id'), table_name='ancestry_defs')
    op.drop_table('ancestry_defs')
    # ### end Alembic commands ###
